### ISSUE TITLE
A suggestion for power saving

### ISSUE THREAD

**Issue by ellnic** [Hasodikis/T480S-Hackintosh#1]
Something I have noticed that may help you in your power saving efforts is a process called `PerfPowerServices`

I can't seem to find out much about it, except the man page:

```
PerfPowerServices – manages structured log archives that enable retrieval
     of system power and performance data.
```

It can sometimes consume a LOT of CPU time:

![Screenshot 2023-09-16 at 11 54 39](https://github.com/Hasodikis/T480S-Hackintosh/assets/16370944/5cfd60d0-0340-4bce-9670-0de2622d67e5)
![Screenshot 2023-09-16 at 12 18 18](https://github.com/Hasodikis/T480S-Hackintosh/assets/16370944/59334125-28f5-4bb5-a4c8-3366ae32d807)

Please note that the percentages above are Unix style (up to 800%) here is what I usually look at which is 0-100:

![Screenshot 2023-09-16 at 11 56 53](https://github.com/Hasodikis/T480S-Hackintosh/assets/16370944/3e59f258-8148-43e1-821c-d5a1a5079904)

In these examples above, it's actually quite low. I have seen it as much at 60% in iStat menu when set to 0-100!

You can find many complaints about it consuming even more:

https://discussions.apple.com/thread/250610012
https://discussions.apple.com/thread/254882216
https://github.com/profzei/Matebook-X-Pro-2018/issues/147

To me, it seems like a totally useless service and I wanted to try disabling it. BUT here's comes the problem, I have tried disabling it but SIP keeps renabling it, so I would welcome any suggestions you have. 

If you use `launchctl unload /System/Library/LaunchDaemons/com.apple.PerfPowerServices.plist` and `launchctl unload /System/Library/LaunchDaemons/com.apple.PerfPowerServicesExtended.plist` it errors due to SIP, so I rebooted into recovery and disabled SIP and mounted the volume as rw:

```
csrutil disable
csrutil authenticated-root disable
mount -uw /Volumes/MacOS
```
Then tried moving them out of the directory, BUT they come back (yeah, nice one Apple!). This new level of system protection is new to me as I have moved to Ventura from a much older Mac OS version (High Sierra). With my old system you could just `sudo spctl --master-disable` but this new locked down root and agressive SIP is an absolute PITA!

I was thinking about a cron job to monitor and kill it, but I would like to try and avoid that.. I don't understand why Apple won't let us disable it. What's the point in having a command to disable SIP, if the changes aren't permanent 👎 

I'll keep looking at this, but if you find out anything about what it does or how to disable it, let me know! :)

**Comment by Hasodikis** [comment]
I have noticed this process in the past hoping up from time to time, but it's very rare and lasts for a minuscule amount of time (at least in my laptops). 
Most of the time it stays at 0,00 or 0,2 % CPU. 

In MacOS editions with SIP you just can' t disable it. It will always reenable.

**Comment by ellnic** [comment]
> In MacOS editions with SIP you just can' t disable it. It will always reenable.

Wow. I can understand SIP from a malicious code point of view, but not allowing the user to disable a logging daemon is ridiculous. Especially when some users report it to be consuming 100% CPU time and running their MacBooks hot!
