### ISSUE TITLE
Can you add YogaSMC support?

### ISSUE THREAD

**Issue by ereve** [Hasodikis/T480S-Hackintosh#2]
Hello, first of all thank you for sharing your nice EFI settings.
It works flawlessly. External monitor output, especially via USB-c port, also works well. Love it.

I found that your EFI configuration does not include [YogaSMC](https://github.com/zhen-zen/YogaSMC) which can control battery  threshold.
I manually included kext and tried to set battery charging limit but it doesn't worked. I think it's blocked to write in EC for some reason.
Can you check this out please? Thank you.

**Comment by Hasodikis** [comment]
I have no intention to include YogaSMC support. 
It sucks ... it stays without updates for a long time.... it never worked properly for me. 

A kext is not enough. 
You have to enable a SSDT. 

Check other EFIS for t480s in github that use it and use the SSDT.
